kafka:
  fullnameOverride: kafka       # ім'я сервісу (хост по якому можна звертатись до брокера)
  numPartitions: 3              # кількість розділів визначає скільки консьюмерів може бути в топіка одночасно
  autoCreateTopicsEnable: false # заборонити автоматичне створення топіків, вони мають визначатись явно, в списку нижче
  provisioning:
    enabled: true               # при запуску будуть створені перелічені топіки
    topics:
      - name: test

microservises:
  client:
    image:
      name: client
      tag: 0.1
    service:
      ports:
        - name: http
          containerPort: 80
          port: 80
    ingress:
      path: /
      port: http

  movies:
    replicaCount: 1
    image:
      name: movies
      tag: 0.1
    service:
      ports:
        - name: http
          containerPort: 8080
          port: 80
    ingress:
      path: /api/movies
      port: http

  payments:
    replicaCount: 1
    image:
      name: payments
      tag: 0.1
    service:
      ports:
        - name: http
          containerPort: 8080
          port: 80
    ingress:
      path: /api/payments
      port: http


